[env]
OPENCV_INCLUDE_PATHS="C:\\tools\\opencv\\build\\include"
OPENCV_LINK_LIBS="opencv_world4100"
OPENCV_LINK_PATHS="C:\\tools\\opencv\\build\\x64\\vc16\\lib"
LIBCLANG_PATH="C:\\Program Files\\LLVM\\lib"